[[plugins]]
repo = 'Shougo/dein.vim'

#ソースから選択肢アクションを適用
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'


#素敵なカラースキーム
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'itchyny/lightline.vim'

#TODO 
[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'vim-scripts/ShowMarks'

