[[plugins]]
repo = 'Shougo/dein.vim'

#ソースから選択肢アクションを適用
[[plugins]]
repo = 'Shougo/unite.vim'

#素敵なカラースキーム
[[plugins]]
repo = 'tomasr/molokai'

#クオートで囲ったり消したり
[[plugins]]
repo = 'surround.vim'
[[plugins]]
repo = 'mattn/emmet-vim'

#スニペット
[[plugins]]
repo = 'Shougo/neocomplcache'
[[plugins]]
repo = 'Shougo/neosnippet'

#線画
[[plugins]]
repo = 'DrawIt'

#コメント非表示
#[[plugins]]
#repo = 'naoty/vim-folcom'

#TODO めっちゃ重い
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
#name = 'lang/python/compl-jedi'
repo = 'davidhalter/jedi-vim'
